### ISSUE TITLE
Calendar does not default to the current date

### ISSUE THREAD

**Issue by jerrellmardis** [ruddarr/app#298]
When opening the Calendar tab, it should scroll to the current date but it does not. This is defined in `CalendarView.initialize()` but  it doesn't seem to be working. Maybe it's trying to scroll to the current date before the items have finished loading?

**Comment by tillkruss** [comment]
This might have been fixed with the calendar refactor in 1.1.1 (223).

**Comment by tillkruss** [comment]
https://github.com/ruddarr/app/commit/15708faa6e2276091d4b70d29eacc22b3d1bcfe4
