### ISSUE TITLE
“Next airing” sorting not accurate

### ISSUE THREAD

**Issue by BlaydeRunner08** [ruddarr/app#302]
When sorting series by "Next Airing", they are not sorted exactly in next airing, and show a different sort when compared to the WebUI sorting.  See attached screenshots:

![App UI](https://github.com/ruddarr/app/assets/25095784/6e5656c6-43b3-48bc-ac95-6e1fc72d45f3)
![Web UI](https://github.com/ruddarr/app/assets/25095784/a73ff3c9-2b9d-4888-ad8d-fc2cda8f84bf)

**Comment by tillkruss** [comment]
Can you send me the JSON from your `/series` endpoint? That would help me identify the exact issue.

**Comment by BlaydeRunner08** [comment]
Hopefully this is what you're looking for?
[Series.json](https://github.com/user-attachments/files/15506126/Series.json)

**Comment by tillkruss** [comment]
I'll take a look at this next week.
