### ISSUE TITLE
Enable "Unknown movie" download in interactive search

### ISSUE THREAD

**Issue by stefan786** [ruddarr/app#307]
When trying to download a movie from interactive search that gives a `Release Rejected – Unknown Movie` message, I get a `404 Server Error (Unable to find matching movie)`.

Grabbing the same movie in Radarr works. 

![image](https://github.com/ruddarr/app/assets/451395/64ee4b55-bb04-430a-9f34-d4c858b0e9ee)
![image](https://github.com/ruddarr/app/assets/451395/58c93a25-0d89-4811-a814-6735b6ed05aa)
![image](https://github.com/ruddarr/app/assets/451395/4854f3cd-c1d8-49f3-8aeb-80c58cdaa30e)

**Comment by tillkruss** [comment]
Closed via 0df608c921507be0c15016b26f2a7c5cbb2917ce.
