### ISSUE TITLE
Can't turn off "Include Health Warnings"

### ISSUE THREAD

**Issue by DaveAlton** [ruddarr/app#312]
Currently, there's no way to turn off health warnings. I can go into my Sonarr/Radarr settings on web and turn them off there in the connection, but Ruddarr keeps resetting that.

**Comment by tillkruss** [comment]
Try disabling them in Ruddarr itself for each instance.

**Comment by tillkruss** [comment]
I see. What's a warning and what's an issue? I can't find any code references for this in Radarr.

**Comment by tillkruss** [comment]
Actually this might overlap with https://github.com/ruddarr/app/issues/303

**Comment by DaveAlton** [comment]
A warning is "An indexer failed". It's something I ignore, and many others do too. An error is "All indexers failed" and it needs to be fixed. In the arrs, errors are red and warnings are yellow.

Yes, I think it'll overlap with that other issue.
