### ISSUE TITLE
Export Calendar View Content to Calendar App Via .ics Subscription

### ISSUE THREAD

**Issue by dorkbuttt** [ruddarr/app#314]
Parcel has this feature that allows me to view my upcoming deliveries through the Calendar app as it provides date information for intended receipt of a package. However, this is accomplished through their parcel.app website.

**Comment by tillkruss** [comment]
I think *arr already supply calendar links.

**Comment by dorkbuttt** [comment]
Ah shit, I gotta find out where this is then when I get my server back up. Thanks!
