### ISSUE TITLE
Show available (free) disk space on server

### ISSUE THREAD

**Issue by b-** [ruddarr/app#316]
Hi,

I'd love to see a counter of free space on my server. I think all of the *arr applications that I control with ruddarr have this somewhere within their UIs, so I have to assume that it can be pulled from the API. 

I tried searching for a similar issue but didn't see one. I hope I'm not posting a duplicate feature request!

**Comment by tillkruss** [comment]
I'd tuck this away in Settings > Instance. Not high on priority list. You're welcome to submit a PR with this feature.

**Comment by tillkruss** [comment]
See #61 and #278.
