### ISSUE TITLE
Multiple instance of Radarr. Duplicates one instance 

### ISSUE THREAD

**Issue by Lasikie** [ruddarr/app#366]
**Describe the bug**
I have two instances of radarr
HTTPS://radarr.xxxxxx.com
HTTPS://radarr4k.xxxxxx.com

both are added to Ruddarr with the correct api’s and addresses.

Ruddarr will only show the contents of the 4k instance.

**To Reproduce**
1. Go to Movies
2. Tap on radarr4k dropdown and switch to radarr
3. See error

**Expected behavior**
I expect to see the contents of the other instance of radarr

**Screenshots / Video**
![IMG_1503](https://github.com/user-attachments/assets/6596aa41-a556-4fc8-95ba-1271e118d373)
![IMG_1502](https://github.com/user-attachments/assets/dff85667-e44b-4398-bd28-dffa10a0c851)

**Environment**
 - iOS version: iOS 18.1 (22B5075a)
 - Ruddar version: 1.3.0 (285)
 - Device: iPhone 15 Pro Max

**Additional context**

**Comment by tillkruss** [comment]
Fixed in 41297fc.
