### ISSUE TITLE
Notification redirection issue

### ISSUE THREAD

**Issue by Peaceout32** [ruddarr/app#367]
**Describe the bug**
Clicking on a notification doesn't take you to the movie/show page if you are not already in that instance. It works fine if you are already in the instance that has this movie/show.

**To Reproduce**
1. Be in instance 1
2. Get a notification from a movie/show that's in instance 2
3. See that you are now at the main page of instance 1 and not in the movie/show page in instance 2

**Expected behavior**
Clicking on the notification should switch you to the correct instance and take you to the movie/show page

**Screenshots / Video**
Can add if needed

**Environment**
 - iOS version: [18.1 RC]
 - Ruddar version: [e.g. 1.3.0 build 286]
 - Device: [iPhone 15 Pro Max]

**Additional context**
N/A

**Comment by tillkruss** [comment]
Instance IDs would need to be added to the web hook: 
https://github.com/ruddarr/app/blob/develop/Ruddarr/Models/Instances/InstanceWebhook.swift#L119

**Comment by tillkruss** [comment]
The *arr payload doesn't contain enough data to determine the instance. I don't think this will ever work unless Radarr/Sonarr supply more data.

**Comment by tillkruss** [comment]
Nevermind, we can use the `instanceName` for this.
