### ISSUE TITLE
UI change request

### ISSUE THREAD

**Issue by seannymurrs** [ruddarr/app#373]
**Is your feature request related to a problem? Please describe.**
When I'm adding a series, I sometimes get confused about the fact that the confirmation button to add the series is labeled "Done".

**Describe the solution you'd like**
I feel like the button should be labeled "Add" or "Add Series" (or something similar).

**Describe alternatives you've considered**
N/A

**Additional context**
See the red circle for exactly which button I'm referring to.
![IMG_0919](https://github.com/user-attachments/assets/a6bef965-e099-4ec3-a814-cf53f0e4e876)

**Comment by tillkruss** [comment]
Done, I agree it's unclear lingo. Please consider leaving a 5-start review.
