### ISSUE TITLE
Transparent navigation bar after adding movie

### ISSUE THREAD

**Issue by vicegold** [ruddarr/app#381]
**Describe the bug**
After adding a movie the detail view clashes with the bottom nav bar. Seems like the bar is losing its background.

**To Reproduce**
1. Add a movie
2. Wait for the detail view to update
3. The tab bar is now transparent

**Expected behavior**
The tab bar should stay on top of the content

**Screenshots / Video**
![image](https://github.com/user-attachments/assets/b18217ec-6d50-4e42-b0f9-d6a83819569d) ![image](https://github.com/user-attachments/assets/a19542c3-86f9-47c7-b157-349613649394)

**Environment**
 - iOS version: 18.1
 - Ruddar version: 1.3.1 (296)
 - Device: iPhone 15 Pro

**Comment by tillkruss** [comment]
Yeah, it's an iOS 18 bug. I don't know what to do about it.
