### ISSUE TITLE
URL not reachable

### ISSUE THREAD

**Issue by cyberbanksy** [ruddarr/app#382]
Here’s the updated bug report with the specifics:

Describe the bug
When using the interactive search feature in Ruddarr to locate a movie already in the movie library, a pop-up error message appears stating, “Are you attempting to connect to a private IP from outside its network?” despite the search results populating. Although the download can eventually be completed, the pop-up keeps reappearing.

To Reproduce

	1.	Go to the movie library in Ruddarr.
	2.	Initiate a search using the interactive search function.
	3.	Observe the pop-up message regarding connection to a private IP.
	4.	Attempt to download from the search results; pop-up continues to appear intermittently.

Expected behavior
The interactive search should allow the movie download without triggering repeated pop-up messages about private IP connections.

Screenshots / Video
![image](https://github.com/user-attachments/assets/1e36d4d6-bf01-454e-baea-584576218f7f)
Environment

	•	iOS version: 18.0.1
	•	Ruddarr version: 1.3.0 build 288
	•	Device: iPhone Pro Max

Additional context
The issue is isolated to Ruddarr; similar actions in Safari or Lunasea do not produce this error, and SABnzbd is fully accessible in these apps without issues.

**Comment by tillkruss** [comment]
Email me your host name and API key so I can reproduce this.

**Comment by tillkruss** [comment]
I'm guessing you have too many "slow" indexers in prowlarr. Try setting your instance to "Slow Instance" in the advanced settings.
